### ISSUE TITLE
How to install xfsprogs?

### ISSUE THREAD

**Issue by aberresch** [bargees/barge-pkg#4]
Hi, I'm trying to install xfsprogs but it always fails with the following error:

`FATAL ERROR: could not find a valid UUID header.
Install the Universally Unique Identifiers development package.
make: *** [/build/buildroot/output/build/xfsprogs-4.5.0/.stamp_configured] Error 1`

I'm using the following command:

`sudo pkg install xfsprogs`

Can u tell me what I'm doing wrong? Or how to install that Universally Unique Identifiers development package?

**Comment by aberresch** [comment]
The following command works:

`sudo pkg install xfsprogs -e BR2_USE_WCHAR=y -e BR2_USE_MMU=y -e BR2_PACKAGE_E2FSPROGS=y -e BR2_PACKAGE_UTIL_LINUX=y -e BR2_PACKAGE_UTIL_LINUX_LIBBLKID=y -e BR2_PACKAGE_UTIL_LINUX_LIBUUID=y`

But the filesystem xfs is still unknown. My goal is to create a Ceph cluster in barge-os. But I get always the following error:

`
DEBUG:ceph-disk:Creating xfs fs on /dev/sdb1
INFO:ceph-disk:Running command: /sbin/mkfs -t xfs -f -i size=2048 -- /dev/sdb1
DEBUG:ceph-disk:Mounting /dev/sdb1 on /var/lib/ceph/tmp/mnt.Q3ZDXK with options noatime,inode64
INFO:ceph-disk:Running command: /bin/mount -t xfs -o noatime,inode64 -- /dev/sdb1 /var/lib/ceph/tmp/mnt.Q3ZDXK
mount: unknown filesystem type 'xfs'
ceph-disk: Mounting filesystem failed: Command '['/bin/mount', '-t', 'xfs', '-o', 'noatime,inode64', '--', '/dev/sdb1', '/var/lib/ceph/tmp/mnt.Q3ZDXK']' returned non-zero exit status 32`

**Comment by aberresch** [comment]
It seems that the os itself doesn't know the xls filesystem.

[root@barge bargee]# cat /proc/filesystems
nodev   sysfs
nodev   rootfs
nodev   tmpfs
nodev   bdev
nodev   proc
nodev   cpuset
nodev   cgroup
nodev   devtmpfs
nodev   binfmt_misc
nodev   securityfs
nodev   sockfs
nodev   pipefs
nodev   ramfs
nodev   rpc_pipefs
nodev   devpts
    ext3
    ext2
    ext4
nodev   hugetlbfs
    vfat
    iso9660
nodev   nfs
nodev   nfs4
    fuseblk
nodev   fuse
nodev   fusectl
nodev   overlay
nodev   9p
nodev   pstore
nodev   mqueue
nodev   vboxsf

How can I install the xls module in barge-os?

**Comment by aberresch** [comment]
OK, found out that I probably need to enable XFS fs in the kernel.config!

**Comment by ailispaw** [comment]
@aberresch That seems right.
I strip out some kernel modules to reduce the size of OS.
But I can add xfs module if it's not a big impact of size.
Could you tell me the advantage of Ceph? I'm interested in Ceph.
Are there any other requirements for Ceph?

**Comment by ailispaw** [comment]
I try to use https://github.com/ceph/ceph-docker to learn about Ceph.
[ceph/demo](https://github.com/ceph/ceph-docker/tree/master/ceph-releases/jewel/ubuntu/14.04/demo) seems to work fine with normal barge-os.

**Comment by ailispaw** [comment]
It looks like Ceph can work on ext4 as well as xfs.
On the other hand, it may need other kernel config as a Ceph client.

```
CONFIG_CEPH_LIB
CONFIG_BLK_DEV_RBD
CONFIG_CEPH_FS
```

**Comment by ailispaw** [comment]
Anyway, please let me know what you need in kernel.config.
I love to support you and will consider it.

**Comment by ailispaw** [comment]
For xfsprogs package, you don't need `BR2_PACKAGE_E2FSPROGS` as [xfsprogs/Config.in](https://github.com/buildroot/buildroot/blob/master/package/xfsprogs/Config.in).

And because [xfsprogs/xfsprogs.mk](https://github.com/buildroot/buildroot/blob/master/package/xfsprogs/xfsprogs.mk) has `XFSPROGS_DEPENDENCIES = util-linux`, the simplest version of the command line is;

`sudo pkg build -f xfsprogs -e BR2_PACKAGE_UTIL_LINUX_LIBBLKID=y -e BR2_PACKAGE_UTIL_LINUX_LIBUUID=y`

It's tricky, isn't it? Sorry about this.

**Comment by aberresch** [comment]
No problem, thx. I'm also a newbie in Ceph and want to play a little bit with it. I also tried the ceph/demo image now and it works. For the first time I tried the ceph/daemon image and start  a container for each service. But the OSD service was the one who needs xfs, etc. I will continue with the ceph/demo image now. Thanks for your support.

**Comment by ailispaw** [comment]
You're welcome. Please let me know if your need anything on Barge.
